version: '2'
services:

  flight-status-elk:
    build: .
    container_name: flight-status-elk
    ports:
      - "8080:8080"
      - "8787:8787"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    restart: no
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:8.11.0
      restart: no
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch                                   # kibana will start when elasticsearch has started

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local